# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [1]:
%pip install beautifulsoup4 requests pandas

Requirement already satisfied: beautifulsoup4 in c:\Users\hp\anaconda3\Lib\site-packages (4.15.0)
Requirement already satisfied: requests in c:\Users\hp\anaconda3\Lib\site-packages (2.34.2)
Requirement already satisfied: pandas in c:\Users\hp\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\hp\anaconda3\Lib\site-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\Users\hp\anaconda3\Lib\site-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\hp\anaconda3\Lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\hp\anaconda3\Lib\site-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\hp\anaconda3\Lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\hp\anaconda3\Lib\site-packages (from requests) (2026.7.22)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\hp\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\hp\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\hp\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\hp\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [7]:
url = "https://books.toscrape.com/"
response = requests.get(url)

soup = BeautifulSoup(response.content, "html.parser")

In [8]:
cards = soup.find_all("article", class_="product_pod")

In [9]:
len(cards)

20

In [10]:
cards[0]

<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [11]:
len(cards)

20

In [12]:
cards[0].find("h3").find("a")["title"]

'A Light in the Attic'

In [13]:
cards[0].find("p", class_="price_color").text

'£51.77'

In [ ]:
# precio
cards[0].find("p", class_="price_color").text.replace("£", "")

'51.77'

In [16]:
float(cards[0].find("p", class_="price_color").text.replace("£", ""))

51.77

In [17]:
# rating
cards[0].find("p", class_="star-rating")

<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>

In [18]:
cards[0].find("p", class_="star-rating").get("class", [])

['star-rating', 'Three']

In [19]:
cards[0].find("p", class_="star-rating").get("class", [])[1]

'Three'

In [21]:
# Convertir el rating a número
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

In [22]:
rating_text = cards[0].find("p", class_="star-rating").get("class", [])[1]

In [23]:
rating = rating_map[rating_text]

In [24]:
rating

3

In [ ]:
# disponibilidad
cards[0].find("p", class_="instock availability").text

'\n\n    \n        In stock\n    \n'

In [26]:
availability = cards[0].find("p", class_="instock availability").text.strip()

In [27]:
availability = cards[0].find("p", class_="instock availability").text.strip()

In [ ]:
#entrar en la página del libro individual
book_link = cards[0].find("h3").find("a").get("href")

In [30]:
book_link

'catalogue/a-light-in-the-attic_1000/index.html'

In [31]:
book_url = "https://books.toscrape.com/" + book_link

In [32]:
response2 = requests.get(book_url)
soup2 = BeautifulSoup(response2.content, "html.parser")

In [33]:
book_url

'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html'

In [34]:
#UPC

soup2.find("td").text

'a897fe39b1053632'

In [35]:
upc = soup2.find("td").text

In [36]:
#Sacar el género
soup2.find("ul", class_="breadcrumb")

<ul class="breadcrumb">
<li>
<a href="../../index.html">Home</a>
</li>
<li>
<a href="../category/books_1/index.html">Books</a>
</li>
<li>
<a href="../category/books/poetry_23/index.html">Poetry</a>
</li>
<li class="active">A Light in the Attic</li>
</ul>

In [37]:
soup2.find("ul", class_="breadcrumb").find_all("a")

[<a href="../../index.html">Home</a>,
 <a href="../category/books_1/index.html">Books</a>,
 <a href="../category/books/poetry_23/index.html">Poetry</a>]

In [38]:
genre = soup2.find("ul", class_="breadcrumb").find_all("a")[2].text

In [39]:
genre

'Poetry'

In [40]:
#sacar la descripción
soup2.find("div", id="product_description")

<div class="sub-header" id="product_description">
<h2>Product Description</h2>
</div>

In [41]:
description = soup2.find("div", id="product_description").find_next_sibling("p").text

In [42]:
description

"It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more"

In [51]:
titles = []
prices = []
ratings = []
availability_all = []
upcs = []
genres = []
descriptions = []

In [45]:
for card in cards:
    title = card.find("h3").find("a")["title"]
    titles.append(title)

In [46]:
len(titles)

20

In [48]:
titles[:5]

['A Light in the Attic',
 'Tipping the Velvet',
 'Soumission',
 'Sharp Objects',
 'Sapiens: A Brief History of Humankind']

In [52]:
for card in cards:
    title = card.find("h3").find("a")["title"]
    titles.append(title)

    price = float(card.find("p", class_="price_color").text.replace("£", ""))
    prices.append(price)

    rating_text = card.find("p", class_="star-rating").get("class", [])[1]
    rating = rating_map[rating_text]
    ratings.append(rating)

    availability = card.find("p", class_="instock availability").text.strip()
    availability_all.append(availability)

In [ ]:
#ojo!:como ya había ejecutado antes un for que añadió los títulos
#vuelvo a ejecutar primero la celda donde inicializas las listas vacías

print(len(titles))
print(len(prices))
print(len(ratings))
print(len(availability_all))

20
20
20
20

In [57]:
for card in cards:
    title = card.find("h3").find("a")["title"]
    titles.append(title)

    price = float(card.find("p", class_="price_color").text.replace("£", ""))
    prices.append(price)

    rating_text = card.find("p", class_="star-rating").get("class", [])[1]
    rating = rating_map[rating_text]
    ratings.append(rating)

    availability = card.find("p", class_="instock availability").text.strip()
    availability_all.append(availability)

    book_link = card.find("h3").find("a").get("href")
    book_url = "https://books.toscrape.com/" + book_link

    response2 = requests.get(book_url)
    soup2 = BeautifulSoup(response2.content, "html.parser")

    upc = soup2.find("td").text
    upcs.append(upc)

    genre = soup2.find("ul", class_="breadcrumb").find_all("a")[2].text
    genres.append(genre)

    description = soup2.find("div", id="product_description").find_next_sibling("p").text
    descriptions.append(description)

In [55]:
titles = []
prices = []
ratings = []
availability_all = []
upcs = []
genres = []
descriptions = []

In [58]:
print(len(titles))
print(len(prices))
print(len(ratings))
print(len(availability_all))
print(len(upcs))
print(len(genres))
print(len(descriptions))

20
20
20
20
20
20
20

In [59]:
#Crear el DataFrame

books_dict = {
    "UPC": upcs,
    "Title": titles,
    "Price (£)": prices,
    "Rating": ratings,
    "Genre": genres,
    "Availability": availability_all,
    "Description": descriptions
}

df = pd.DataFrame(books_dict)

In [61]:
df.head()

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,a897fe39b1053632,A Light in the Attic,51.77,3,Poetry,In stock,It's hard to imagine a world without A Light i...
1,90fa61229261140a,Tipping the Velvet,53.74,1,Historical Fiction,In stock,"""Erotic and absorbing...Written with starling ..."
2,6957f44c3847a760,Soumission,50.10,1,Fiction,In stock,"Dans une France assez proche de la nôtre, un h..."
3,e00eb4fd7b871a48,Sharp Objects,47.82,4,Mystery,In stock,"WICKED above her hipbone, GIRL across her hear..."
4,4165285e1663650f,Sapiens: A Brief History of Humankind,54.23,5,History,In stock,From a renowned historian comes a groundbreaki...

In [62]:
df.shape

(20, 7)

In [64]:
def scrape_books(min_rating, max_price):
    url = "https://books.toscrape.com/"

In [65]:
def scrape_books(min_rating, max_price):
    url = "https://books.toscrape.com/"
    books = []

    while url:
        response = requests.get(url)
        soup = BeautifulSoup(response.content, "html.parser")

        cards = soup.find_all("article", class_="product_pod")

In [74]:
from urllib.parse import urljoin

In [75]:
def scrape_books(min_rating, max_price):
    url = "https://books.toscrape.com/"
    books = []

    while url:
        response = requests.get(url)
        soup = BeautifulSoup(response.content, "html.parser")

        cards = soup.find_all("article", class_="product_pod")

        for card in cards:
            title = card.find("h3").find("a")["title"]

            price = float(
                card.find("p", class_="price_color").text.replace("£", "")
            )

            rating_text = card.find(
                "p", class_="star-rating"
            ).get("class", [])[1]

            rating = rating_map[rating_text]

            if rating >= min_rating and price <= max_price:
                print(title, price, rating)
            next_button = soup.find("li", class_="next")
        next_button = soup.find("li", class_="next")

        if next_button:
            next_link = next_button.find("a").get("href")
            url = urljoin(url, next_link)
        else:
            url = None

In [78]:
def scrape_books(min_rating, max_price):
    url = "https://books.toscrape.com/"
    books = []

    while url:
        response = requests.get(url)
        soup = BeautifulSoup(response.content, "html.parser")

        cards = soup.find_all("article", class_="product_pod")

        for card in cards:
            title = card.find("h3").find("a")["title"]

            price = float(
                card.find("p", class_="price_color").text.replace("£", "")
            )

            rating_text = card.find(
                "p", class_="star-rating"
            ).get("class", [])[1]

            rating = rating_map[rating_text]

            if rating >= min_rating and price <= max_price:
                book_link = card.find("h3").find("a").get("href")
                book_url = urljoin(url, book_link)

                response2 = requests.get(book_url)
                soup2 = BeautifulSoup(response2.content, "html.parser")

                availability = card.find(
                    "p", class_="instock availability"
                ).text.strip()

                upc = soup2.find("td").text

                genre = soup2.find(
                    "ul", class_="breadcrumb"
                ).find_all("a")[2].text

                description_section = soup2.find(
                    "div", id="product_description"
                )

                if description_section:
                    description = description_section.find_next_sibling("p").text
                else:
                    description = ""

                books.append({
                    "UPC": upc,
                    "Title": title,
                    "Price (£)": price,
                    "Rating": rating,
                    "Genre": genre,
                    "Availability": availability,
                    "Description": description
                })

        next_button = soup.find("li", class_="next")

        if next_button:
            next_link = next_button.find("a").get("href")
            url = urljoin(url, next_link)
        else:
            url = None

    return pd.DataFrame(books)

FUNCIÓN
│
├── WHILE → recorre las páginas
│   │
│   ├── FOR → recorre los libros de esa página
│   │   │
│   │   └── IF → si cumple rating y precio
│   │          └── recoge datos y guarda libro
│   │
│   └── NEXT → pasa a la página siguiente
│
└── RETURN → convierte los libros en DataFrame

In [79]:
result = scrape_books(4, 20)

In [80]:
result

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock,Aaron Ledbetter’s future had been planned out ...
1,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,5,Spirituality,In stock,"In The Four Agreements, don Miguel Ruiz reveal..."
2,6be3beb0793a53e7,Sophie's World,15.94,5,Philosophy,In stock,A page-turning novel that is also an explorati...
3,657fe5ead67a7767,Untitled Collection: Sabbath Poems 2014,14.27,4,Poetry,In stock,"More than thirty-five years ago, when the weat..."
4,51653ef291ab7ddc,This One Summer,19.49,4,Sequential Art,In stock,"Every summer, Rose goes with her mom and dad t..."
...,...,...,...,...,...,...,...
70,9c96cd1329fbd82d,The Zombie Room,19.69,5,Default,In stock,An unlikely bond is forged between three men f...
71,b78deb463531d078,The Silent Wife,12.34,5,Fiction,In stock,A chilling psychological thriller about a marr...
72,4280ac3eab57aa5d,The Girl You Lost,12.29,5,Mystery,In stock,Eighteen years ago your baby daughter was snat...
73,29fc016c459aeb14,The Edge of Reason (Bridget Jones #2),19.18,4,Womens Fiction,In stock,Monday 27 January“7:15 a.m. Hurrah! The wilder...
74,19fec36a1dfb4c16,A Spy's Devotion (The Regency Spies of London #1),16.97,5,Historical Fiction,In stock,"In England’s Regency era, manners and elegance..."

In [81]:
result.shape

(75, 7)

In [83]:
result[["Title", "Price (£)", "Rating"]].head(10)

                                               Title  Price (£)  Rating
0                                        Set Me Free      17.46       5
1  The Four Agreements: A Practical Guide to Pers...      17.66       5
2                                     Sophie's World      15.94       5
3            Untitled Collection: Sabbath Poems 2014      14.27       4
4                                    This One Summer      19.49       4
5                                             Thirst      17.27       5
6  Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...      13.61       5
7   Princess Between Worlds (Wide-Awake Princess #5)      13.34       5
8  Outcast, Vol. 1: A Darkness Surrounds Him (Out...      15.44       4
9  Mama Tried: Traditional Italian Cooking for th...      14.02       4

In [84]:
result

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock,Aaron Ledbetter’s future had been planned out ...
1,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,5,Spirituality,In stock,"In The Four Agreements, don Miguel Ruiz reveal..."
2,6be3beb0793a53e7,Sophie's World,15.94,5,Philosophy,In stock,A page-turning novel that is also an explorati...
3,657fe5ead67a7767,Untitled Collection: Sabbath Poems 2014,14.27,4,Poetry,In stock,"More than thirty-five years ago, when the weat..."
4,51653ef291ab7ddc,This One Summer,19.49,4,Sequential Art,In stock,"Every summer, Rose goes with her mom and dad t..."
...,...,...,...,...,...,...,...
70,9c96cd1329fbd82d,The Zombie Room,19.69,5,Default,In stock,An unlikely bond is forged between three men f...
71,b78deb463531d078,The Silent Wife,12.34,5,Fiction,In stock,A chilling psychological thriller about a marr...
72,4280ac3eab57aa5d,The Girl You Lost,12.29,5,Mystery,In stock,Eighteen years ago your baby daughter was snat...
73,29fc016c459aeb14,The Edge of Reason (Bridget Jones #2),19.18,4,Womens Fiction,In stock,Monday 27 January“7:15 a.m. Hurrah! The wilder...
74,19fec36a1dfb4c16,A Spy's Devotion (The Regency Spies of London #1),16.97,5,Historical Fiction,In stock,"In England’s Regency era, manners and elegance..."

In [ ]:
#  comprobación final

(result["Rating"] >= 4).all(), (result["Price (£)"] <= 20).all()

(np.True_, np.True_)